services:
    rshief.pubsub.topic:
        class: Bangpound\Bundle\PubsubBundle\Admin\TopicAdmin
        arguments: [ ~ , '%sputnik_pubsub.model.topic.class%', 'RshiefPubsubBundle:CRUD' ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: PubSub, label: Topic }
        calls:
            - [ setTranslationDomain, [ 'RshiefPubsubBundle' ] ]
            - [ setHubSubscriber, [ '@sputnik_pubsub.hub_subscriber' ] ]
