parameters:
    bangpound_pubsub.notification_listener.class: Bangpound\Bundle\PubsubBundle\EventListener\PubsubNotification
    bangpound_pubsub.form.type.hub_name.class: Bangpound\Bundle\PubsubBundle\Form\Type\HubNameType
    bangpound_pubsub.persistent_atom_entry.class: Bangpound\Bundle\PubsubBundle\CouchDocument\AtomEntry

services:
    hub.superfeedr:
        class: Sputnik\Bundle\PubsubBundle\Hub\SuperfeedrHub
        arguments: [ superfeedr, http://superfeedr.com/hubbub, %superfeedr_user%, %superfeedr_password% ]
        tags:
            - { name: sputnik_pubsub.hub }

    hub.blogger:
        class: Sputnik\Bundle\PubsubBundle\Hub\Hub
        arguments: [ blogger, http://pubsubhubbub.appspot.com ]
        tags:
            - { name: sputnik_pubsub.hub }

    hub.tumblr:
        class: Sputnik\Bundle\PubsubBundle\Hub\Hub
        arguments: [ tumblr, http://tumblr.superfeedr.com ]
        tags:
            - { name: sputnik_pubsub.hub }

    bangpound_pubsub.notification_listener:
        arguments: [ "@sonata.notification.backend" ]
        class: %bangpound_pubsub.notification_listener.class%
        tags:
            - { name: kernel.event_subscriber }

    bangpound_pubsub.form.type.hub_name:
        class: %bangpound_pubsub.form.type.hub_name.class%
        arguments:
            - "@sputnik_pubsub.hub_provider"
        tags:
            - { name: form.type, alias: hub_name }
